In [1]:
import numpy as np
import pandas as pd


In [2]:
dict1 = {
    "name":['harry','rohan','shlok','shubh'],
    "marks":[33,44,55,22],
    "city":['mumbai','pune','tripura','raigad']
}

In [3]:
df= pd.DataFrame(dict1)

In [4]:
df

name  marks     city
0  harry     33   mumbai
1  rohan     44     pune
2  shlok     55  tripura
3  shubh     22   raigad

In [7]:
df.to_csv('first.csv')

In [8]:
df.to_csv('first2.csv',index=False)

In [10]:
df.head(2)

name  marks    city
0  harry     33  mumbai
1  rohan     44    pune

In [11]:
df.tail(3)

name  marks     city
1  rohan     44     pune
2  shlok     55  tripura
3  shubh     22   raigad

In [12]:
df.describe()

marks
count   4.000000
mean   38.500000
std    14.200939
min    22.000000
25%    30.250000
50%    38.500000
75%    46.750000
max    55.000000

In [27]:
arr=np.array([[22,33,445,55],[2,44,55,66]])

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr

array([[ 22,  33, 445,  55],
       [  2,  44,  55,  66]])

In [32]:
shlok= pd.read_csv('first.csv')

In [33]:
shlok

Unnamed: 0   name  marks     city
0           0  harry     33   mumbai
1           1  rohan     44     pune
2           2  shlok     55  tripura
3           3  shubh     22   raigad

In [34]:
shlok['name']

0    harry
1    rohan
2    shlok
3    shubh
Name: name, dtype: object

In [35]:
shlok['name'][0]='adya'

C:\Users\Shlok\AppData\Local\Temp/ipykernel_18008/1724538301.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shlok['name'][0]='adya'


In [36]:
shlok

Unnamed: 0   name  marks     city
0           0   adya     33   mumbai
1           1  rohan     44     pune
2           2  shlok     55  tripura
3           3  shubh     22   raigad

In [37]:
shlok.index=['first',2,3,5]

In [41]:
shlok.to_csv('sa',index=False)

In [42]:
shlok

Unnamed: 0   name  marks     city
first           0   adya     33   mumbai
2               1  rohan     44     pune
3               2  shlok     55  tripura
5               3  shubh     22   raigad

In [48]:
 c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)

In [50]:
c.sum(axis=0)

array([[ 4.5,  4. ,  4. ],
       [ 8. , 10. , 12. ]])

In [51]:
c


array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])